  name: status_dp_app
  description: Status DP App
  publish_to: 'none'
  version: 1.0.0+1

  environment:
    sdk: '>=3.0.0 <4.0.0'

  dependencies:
    flutter:
      sdk: flutter
    http: ^1.1.0
    intl: ^0.19.0
    mocktail: ^1.0.4
    supabase_flutter: ^2.4.0
    collection: ^1.17.0

  dev_dependencies:
    flutter_test:
      sdk: flutter
    flutter_lints: ^2.0.0

  flutter:
    uses-material-design: true