import 'package:intl/intl.dart';

class Planner {
  final int id;
  final int usuarioId;
  final int statusId;
  final String? horario1;
  final DateTime? data1;
  final String? informacao1;
  final String? horario2;
  final DateTime? data2;
  final String? informacao2;
  final String? horario3;
  final DateTime? data3;
  final String? informacao3;
  final String? horario4;
  final DateTime? data4;
  final String? informacao4;
  final String? horario5;
  final DateTime? data5;
  final String? informacao5;
  final String? horario6;
  final DateTime? data6;
  final String? informacao6;
  final String? horario7;
  final DateTime? data7;
  final String? informacao7;
  final String? horario8;
  final DateTime? data8;
  final String? informacao8;
  final String? horario9;
  final DateTime? data9;
  final String? informacao9;
  final String? horario10;
  final DateTime? data10;
  final String? informacao10;

  Planner({
    required this.id,
    required this.usuarioId,
    required this.statusId,
    this.horario1,
    this.data1,
    this.informacao1,
    this.horario2,
    this.data2,
    this.informacao2,
    this.horario3,
    this.data3,
    this.informacao3,
    this.horario4,
    this.data4,
    this.informacao4,
    this.horario5,
    this.data5,
    this.informacao5,
    this.horario6,
    this.data6,
    this.informacao6,
    this.horario7,
    this.data7,
    this.informacao7,
    this.horario8,
    this.data8,
    this.informacao8,
    this.horario9,
    this.data9,
    this.informacao9,
    this.horario10,
    this.data10,
    this.informacao10,
  });

  factory Planner.fromJson(Map<String, dynamic> json) {
    return Planner(
      id: json['id'] as int,
      usuarioId: json['usuarioid'] as int,
      statusId: json['statusid'] as int,
      horario1: json['horario1'] as String?,
      data1: json['data1'] != null ? DateTime.parse(json['data1']) : null,
      informacao1: json['informacao1'] as String?,
      horario2: json['horario2'] as String?,
      data2: json['data2'] != null ? DateTime.parse(json['data2']) : null,
      informacao2: json['informacao2'] as String?,
      horario3: json['horario3'] as String?,
      data3: json['data3'] != null ? DateTime.parse(json['data3']) : null,
      informacao3: json['informacao3'] as String?,
      horario4: json['horario4'] as String?,
      data4: json['data4'] != null ? DateTime.parse(json['data4']) : null,
      informacao4: json['informacao4'] as String?,
      horario5: json['horario5'] as String?,
      data5: json['data5'] != null ? DateTime.parse(json['data5']) : null,
      informacao5: json['informacao5'] as String?,
      horario6: json['horario6'] as String?,
      data6: json['data6'] != null ? DateTime.parse(json['data6']) : null,
      informacao6: json['informacao6'] as String?,
      horario7: json['horario7'] as String?,
      data7: json['data7'] != null ? DateTime.parse(json['data7']) : null,
      informacao7: json['informacao7'] as String?,
      horario8: json['horario8'] as String?,
      data8: json['data8'] != null ? DateTime.parse(json['data8']) : null,
      informacao8: json['informacao8'] as String?,
      horario9: json['horario9'] as String?,
      data9: json['data9'] != null ? DateTime.parse(json['data9']) : null,
      informacao9: json['informacao9'] as String?,
      horario10: json['horario10'] as String?,
      data10: json['data10'] != null ? DateTime.parse(json['data10']) : null,
      informacao10: json['informacao10'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    final map = {
      'usuarioid': usuarioId,
      'statusid': statusId,
      'horario1': horario1,
      'data1': data1?.toIso8601String(),
      'informacao1': informacao1,
      'horario2': horario2,
      'data2': data2?.toIso8601String(),
      'informacao2': informacao2,
      'horario3': horario3,
      'data3': data3?.toIso8601String(),
      'informacao3': informacao3,
      'horario4': horario4,
      'data4': data4?.toIso8601String(),
      'informacao4': informacao4,
      'horario5': horario5,
      'data5': data5?.toIso8601String(),
      'informacao5': informacao5,
      'horario6': horario6,
      'data6': data6?.toIso8601String(),
      'informacao6': informacao6,
      'horario7': horario7,
      'data7': data7?.toIso8601String(),
      'informacao7': informacao7,
      'horario8': horario8,
      'data8': data8?.toIso8601String(),
      'informacao8': informacao8,
      'horario9': horario9,
      'data9': data9?.toIso8601String(),
      'informacao9': informacao9,
      'horario10': horario10,
      'data10': data10?.toIso8601String(),
      'informacao10': informacao10,
    };

    // Só inclui o 'id' no JSON se ele for diferente de -1 (ou seja, se for um valor válido do banco)
    if (id != -1) {
      map['id'] = id;
    }

    return map;
  }

  List<Map<String, dynamic>> getEntries() {
    return [
      {'horario': horario1, 'data': data1, 'informacao': informacao1},
      {'horario': horario2, 'data': data2, 'informacao': informacao2},
      {'horario': horario3, 'data': data3, 'informacao': informacao3},
      {'horario': horario4, 'data': data4, 'informacao': informacao4},
      {'horario': horario5, 'data': data5, 'informacao': informacao5},
      {'horario': horario6, 'data': data6, 'informacao': informacao6},
      {'horario': horario7, 'data': data7, 'informacao': informacao7},
      {'horario': horario8, 'data': data8, 'informacao': informacao8},
      {'horario': horario9, 'data': data9, 'informacao': informacao9},
      {'horario': horario10, 'data': data10, 'informacao': informacao10},
    ];
  }

  Planner updateEntry(int index, String? horario, DateTime? data, String? informacao) {
    switch (index) {
      case 0:
        return Planner(
          id: id,
          usuarioId: usuarioId,
          statusId: statusId,
          horario1: horario,
          data1: data,
          informacao1: informacao,
          horario2: horario2,
          data2: data2,
          informacao2: informacao2,
          horario3: horario3,
          data3: data3,
          informacao3: informacao3,
          horario4: horario4,
          data4: data4,
          informacao4: informacao4,
          horario5: horario5,
          data5: data5,
          informacao5: informacao5,
          horario6: horario6,
          data6: data6,
          informacao6: informacao6,
          horario7: horario7,
          data7: data7,
          informacao7: informacao7,
          horario8: horario8,
          data8: data8,
          informacao8: informacao8,
          horario9: horario9,
          data9: data9,
          informacao9: informacao9,
          horario10: horario10,
          data10: data10,
          informacao10: informacao10,
        );
      case 1:
        return Planner(
          id: id,
          usuarioId: usuarioId,
          statusId: statusId,
          horario1: horario1,
          data1: data1,
          informacao1: informacao1,
          horario2: horario,
          data2: data,
          informacao2: informacao,
          horario3: horario3,
          data3: data3,
          informacao3: informacao3,
          horario4: horario4,
          data4: data4,
          informacao4: informacao4,
          horario5: horario5,
          data5: data5,
          informacao5: informacao5,
          horario6: horario6,
          data6: data6,
          informacao6: informacao6,
          horario7: horario7,
          data7: data7,
          informacao7: informacao7,
          horario8: horario8,
          data8: data8,
          informacao8: informacao8,
          horario9: horario9,
          data9: data9,
          informacao9: informacao9,
          horario10: horario10,
          data10: data10,
          informacao10: informacao10,
        );
      case 2:
        return Planner(
          id: id,
          usuarioId: usuarioId,
          statusId: statusId,
          horario1: horario1,
          data1: data1,
          informacao1: informacao1,
          horario2: horario2,
          data2: data2,
          informacao2: informacao2,
          horario3: horario,
          data3: data,
          informacao3: informacao,
          horario4: horario4,
          data4: data4,
          informacao4: informacao4,
          horario5: horario5,
          data5: data5,
          informacao5: informacao5,
          horario6: horario6,
          data6: data6,
          informacao6: informacao6,
          horario7: horario7,
          data7: data7,
          informacao7: informacao7,
          horario8: horario8,
          data8: data8,
          informacao8: informacao8,
          horario9: horario9,
          data9: data9,
          informacao9: informacao9,
          horario10: horario10,
          data10: data10,
          informacao10: informacao10,
        );
      case 3:
        return Planner(
          id: id,
          usuarioId: usuarioId,
          statusId: statusId,
          horario1: horario1,
          data1: data1,
          informacao1: informacao1,
          horario2: horario2,
          data2: data2,
          informacao2: informacao2,
          horario3: horario3,
          data3: data3,
          informacao3: informacao3,
          horario4: horario,
          data4: data,
          informacao4: informacao,
          horario5: horario5,
          data5: data5,
          informacao5: informacao5,
          horario6: horario6,
          data6: data6,
          informacao6: informacao6,
          horario7: horario7,
          data7: data7,
          informacao7: informacao7,
          horario8: horario8,
          data8: data8,
          informacao8: informacao8,
          horario9: horario9,
          data9: data9,
          informacao9: informacao9,
          horario10: horario10,
          data10: data10,
          informacao10: informacao10,
        );
      case 4:
        return Planner(
          id: id,
          usuarioId: usuarioId,
          statusId: statusId,
          horario1: horario1,
          data1: data1,
          informacao1: informacao1,
          horario2: horario2,
          data2: data2,
          informacao2: informacao2,
          horario3: horario3,
          data3: data3,
          informacao3: informacao3,
          horario4: horario4,
          data4: data4,
          informacao4: informacao4,
          horario5: horario,
          data5: data,
          informacao5: informacao,
          horario6: horario6,
          data6: data6,
          informacao6: informacao6,
          horario7: horario7,
          data7: data7,
          informacao7: informacao7,
          horario8: horario8,
          data8: data8,
          informacao8: informacao8,
          horario9: horario9,
          data9: data9,
          informacao9: informacao9,
          horario10: horario10,
          data10: data10,
          informacao10: informacao10,
        );
      case 5:
        return Planner(
          id: id,
          usuarioId: usuarioId,
          statusId: statusId,
          horario1: horario1,
          data1: data1,
          informacao1: informacao1,
          horario2: horario2,
          data2: data2,
          informacao2: informacao2,
          horario3: horario3,
          data3: data3,
          informacao3: informacao3,
          horario4: horario4,
          data4: data4,
          informacao4: informacao4,
          horario5: horario5,
          data5: data5,
          informacao5: informacao5,
          horario6: horario,
          data6: data,
          informacao6: informacao,
          horario7: horario7,
          data7: data7,
          informacao7: informacao7,
          horario8: horario8,
          data8: data8,
          informacao8: informacao8,
          horario9: horario9,
          data9: data9,
          informacao9: informacao9,
          horario10: horario10,
          data10: data10,
          informacao10: informacao10,
        );
      case 6:
        return Planner(
          id: id,
          usuarioId: usuarioId,
          statusId: statusId,
          horario1: horario1,
          data1: data1,
          informacao1: informacao1,
          horario2: horario2,
          data2: data2,
          informacao2: informacao2,
          horario3: horario3,
          data3: data3,
          informacao3: informacao3,
          horario4: horario4,
          data4: data4,
          informacao4: informacao4,
          horario5: horario5,
          data5: data5,
          informacao5: informacao5,
          horario6: horario6,
          data6: data6,
          informacao6: informacao6,
          horario7: horario,
          data7: data,
          informacao7: informacao,
          horario8: horario8,
          data8: data8,
          informacao8: informacao8,
          horario9: horario9,
          data9: data9,
          informacao9: informacao9,
          horario10: horario10,
          data10: data10,
          informacao10: informacao10,
        );
      case 7:
        return Planner(
          id: id,
          usuarioId: usuarioId,
          statusId: statusId,
          horario1: horario1,
          data1: data1,
          informacao1: informacao1,
          horario2: horario2,
          data2: data2,
          informacao2: informacao2,
          horario3: horario3,
          data3: data3,
          informacao3: informacao3,
          horario4: horario4,
          data4: data4,
          informacao4: informacao4,
          horario5: horario5,
          data5: data5,
          informacao5: informacao5,
          horario6: horario6,
          data6: data6,
          informacao6: informacao6,
          horario7: horario7,
          data7: data7,
          informacao7: informacao7,
          horario8: horario,
          data8: data,
          informacao8: informacao,
          horario9: horario9,
          data9: data9,
          informacao9: informacao9,
          horario10: horario10,
          data10: data10,
          informacao10: informacao10,
        );
      case 8:
        return Planner(
          id: id,
          usuarioId: usuarioId,
          statusId: statusId,
          horario1: horario1,
          data1: data1,
          informacao1: informacao1,
          horario2: horario2,
          data2: data2,
          informacao2: informacao2,
          horario3: horario3,
          data3: data3,
          informacao3: informacao3,
          horario4: horario4,
          data4: data4,
          informacao4: informacao4,
          horario5: horario5,
          data5: data5,
          informacao5: informacao5,
          horario6: horario6,
          data6: data6,
          informacao6: informacao6,
          horario7: horario7,
          data7: data7,
          informacao7: informacao7,
          horario8: horario8,
          data8: data8,
          informacao8: informacao8,
          horario9: horario,
          data9: data,
          informacao9: informacao,
          horario10: horario10,
          data10: data10,
          informacao10: informacao10,
        );
      case 9:
        return Planner(
          id: id,
          usuarioId: usuarioId,
          statusId: statusId,
          horario1: horario1,
          data1: data1,
          informacao1: informacao1,
          horario2: horario2,
          data2: data2,
          informacao2: informacao2,
          horario3: horario3,
          data3: data3,
          informacao3: informacao3,
          horario4: horario4,
          data4: data4,
          informacao4: informacao4,
          horario5: horario5,
          data5: data5,
          informacao5: informacao5,
          horario6: horario6,
          data6: data6,
          informacao6: informacao6,
          horario7: horario7,
          data7: data7,
          informacao7: informacao7,
          horario8: horario8,
          data8: data8,
          informacao8: informacao8,
          horario9: horario9,
          data9: data9,
          informacao9: informacao9,
          horario10: horario,
          data10: data,
          informacao10: informacao,
        );
      default:
        return this;
    }
  }
}